# -*- coding: utf-8 -*-
"""AI compute industry-chain metadata.

This module is intentionally independent from the market fetcher. The first
version infers a company stage from the current semiconductor watchlist; when
the two user-provided industry-chain matrices arrive, their listed-company
coverage can be encoded here without touching the dashboard rendering code.
"""

CHAIN_STAGES = [
    ("accelerator", "AI加速器/核心芯片", "AI accelerators & core silicon"),
    ("memory", "HBM/存储", "HBM & memory"),
    ("interconnect", "高速互连/光通信", "High-speed interconnect & optics"),
    ("foundry", "晶圆制造/代工", "Foundry & wafer manufacturing"),
    ("packaging", "先进封装/封测", "Advanced packaging & OSAT"),
    ("equipment", "半导体设备", "Semiconductor equipment"),
    ("materials", "材料/零部件", "Materials & components"),
    ("power", "电源/功率/散热", "Power, power devices & cooling"),
    ("cloud", "云厂商/数据中心", "Cloud & data centers"),
    ("server", "服务器/OEM/ODM", "Servers, OEM & ODM"),
    ("edge", "边缘AI/应用芯片", "Edge AI & application silicon"),
    ("other", "其他算力产业链", "Other compute-chain exposure"),
]

STAGE_BY_KEY = {key: {"zh": zh, "en": en} for key, zh, en in CHAIN_STAGES}

COUNTRY_EN = {
    "美国": "United States",
    "中国大陆": "Mainland China",
    "中国台湾": "Taiwan, China",
    "韩国": "South Korea",
    "日本": "Japan",
    "荷兰": "Netherlands",
    "德国": "Germany",
    "法国": "France",
    "比利时": "Belgium",
    "挪威": "Norway",
    "瑞士": "Switzerland",
    "英国": "United Kingdom",
    "以色列": "Israel",
    "马来西亚": "Malaysia",
    "新加坡": "Singapore",
    "爱尔兰": "Ireland",
    "加拿大": "Canada",
    "澳大利亚": "Australia",
    "南非": "South Africa",
    "哥伦比亚": "Colombia",
    "沙特阿拉伯": "Saudi Arabia",
    "印度": "India",
    "意大利": "Italy",
    "瑞典": "Sweden",
    "西班牙": "Spain",
    "芬兰": "Finland",
}

SEGMENT_EN = {
    "GPU/AI芯片": "GPU / AI accelerator",
    "CPU/GPU": "CPU / GPU",
    "IDM": "Integrated device manufacturer",
    "手机SoC": "Mobile SoC",
    "网络/定制AI": "Networking / custom AI silicon",
    "模拟": "Analog IC",
    "存储": "Memory",
    "数据中心芯片": "Data-center silicon",
    "功率": "Power devices",
    "MCU": "MCU",
    "设备": "Equipment",
    "检测设备": "Inspection equipment",
    "EDA": "EDA software",
    "测试设备": "Test equipment",
    "代工": "Foundry",
    "射频": "RF",
    "电源管理": "Power management",
    "AI互连": "AI interconnect",
    "高速互连": "High-speed interconnect",
    "光电": "Optoelectronics",
    "材料": "Materials",
    "封测": "Packaging and testing",
    "内存接口": "Memory interface",
    "FPGA": "FPGA",
    "IoT芯片": "IoT silicon",
    "碳化硅": "Silicon carbide",
    "探针卡": "Probe cards",
    "离子注入": "Ion implantation",
    "时钟芯片": "Timing IC",
    "电源芯片": "Power IC",
    "音频芯片": "Audio IC",
    "触控/连接": "Touch / connectivity",
    "分立器件": "Discrete devices",
    "射频/光": "RF / optical",
    "LoRa/信号链": "LoRa / signal chain",
    "IP架构": "IP architecture",
    "光刻机": "Lithography",
    "特色代工": "Specialty foundry",
    "量测": "Metrology",
    "显示驱动": "Display driver",
    "网络芯片": "Networking IC",
    "ASIC设计": "ASIC design",
    "DRAM": "DRAM",
    "IDM/存储": "IDM / memory",
    "存储/HBM": "Memory / HBM",
    "HBM设备": "HBM equipment",
    "退火设备": "Annealing equipment",
    "切割研磨": "Dicing / grinding",
    "清洗设备": "Cleaning equipment",
    "EUV检测": "EUV inspection",
    "硅片/材料": "Wafer / materials",
    "硅片": "Silicon wafer",
    "NAND": "NAND",
    "ALD设备": "ALD equipment",
    "先进封装设备": "Advanced packaging equipment",
    "功率/车规": "Power / automotive",
    "MOCVD": "MOCVD",
    "车规芯片": "Automotive IC",
    "光刻配套": "Lithography support",
    "SOI衬底": "SOI substrate",
    "车规传感": "Automotive sensors",
    "蓝牙芯片": "Bluetooth IC",
    "定位芯片": "Positioning IC",
    "真空阀件": "Vacuum valves",
    "智驾芯片": "Autonomous driving silicon",
    "FPGA/安全": "FPGA / security",
    "CIS图像传感": "CIS image sensor",
    "刻蚀设备": "Etching equipment",
    "CPU/DCU": "CPU / DCU",
    "AI芯片": "AI accelerator",
    "NOR/MCU": "NOR / MCU",
    "安全芯片": "Security IC",
    "功率IDM": "Power IDM",
    "薄膜设备": "Thin-film equipment",
    "CMP设备": "CMP equipment",
    "CPU": "CPU",
    "AIoT SoC": "AIoT SoC",
    "多媒体SoC": "Multimedia SoC",
    "功率/ODM": "Power / ODM",
    "化合物半导体": "Compound semiconductor",
    "存储/MCU": "Memory / MCU",
    "设备零部件": "Equipment components",
    "云厂商/数据中心": "Cloud / data centers",
    "数据中心": "Data centers",
    "数据中心REIT": "Data-center REIT",
    "服务器/OEM/ODM": "Servers / OEM / ODM",
    "服务器ODM": "Server ODM",
    "数据中心网络": "Data-center networking",
    "数据中心存储": "Data-center storage",
    "电力/散热": "Power and thermal infrastructure",
    "电力管理": "Power management",
    "散热/液冷": "Thermal / liquid cooling",
    "边缘AI/终端": "Edge AI / devices",
    "智能汽车/车端AI": "Autonomous driving / vehicle AI",
    "企业AI平台": "Enterprise AI platform",
    "企业AI软件": "Enterprise AI software",
    "工业自动化/EDA": "Industrial automation / EDA",
    "电力/工程设备": "Power / industrial equipment",
    "电力/发电设备": "Power generation equipment",
    "电力/可再生": "Power / renewables",
    "电力/核能": "Power / nuclear",
    "电力/发电": "Power generation",
    "电力/燃料电池": "Power / fuel cells",
    "电力/电网": "Power grid",
    "电信网络/边缘": "Telecom network / edge",
    "数据中心投资": "Data-center investment",
    "数据中心/地产基础设施": "Data-center real estate infrastructure",
    "铜/矿业材料": "Copper / mining materials",
    "电力/核能材料": "Nuclear fuel materials",
    "电信/云网基础设施": "Telecom / cloud-network infrastructure",
    "电池/储能": "Battery / energy storage",
    "光模块/光通信": "Optical modules / communications",
    "AI应用/语音": "AI applications / speech",
    "边缘AI/视觉": "Edge AI / vision",
    "工业软件/数据中心": "Industrial software / data centers",
    "PCB/材料": "PCB / materials",
    "光通信/激光": "Optical communications / lasers",
    "电力设备": "Power equipment",
    "能源/电力燃料": "Energy / power fuel",
    "电源/散热/电力": "Power, cooling and electrical systems",
    "工业自动化/量子计算": "Industrial automation / quantum computing",
    "电力/工业基础设施": "Power / industrial infrastructure",
    "能源/电力基础设施": "Energy / power infrastructure",
    "企业AI服务": "Enterprise AI services",
    "数据中心/IT服务": "Data-center / IT services",
    "企业AI数据平台": "Enterprise AI data platform",
    "水处理/数据中心冷却": "Water treatment / data-center cooling",
    "散热/暖通": "Thermal / HVAC",
    "散热/暖通/电力": "Thermal / HVAC / power",
    "边缘AI/应用": "Edge AI / applications",
    "连接器/服务器组件": "Connectors / server components",
    "云厂商/供应链AI": "Cloud / supply-chain AI",
    "安全/边缘AI": "Security / edge AI",
    "能源/数据中心基础设施": "Energy / data-center infrastructure",
    "AI算力租赁": "AI compute leasing",
    "边缘AI/图像传感": "Edge AI / image sensing",
    "散热/楼宇控制": "Thermal / building controls",
    "数据中心地产服务": "Data-center real estate services",
    "电力/配电管理": "Power / distribution management",
    "电子制造/服务器组件": "Electronics manufacturing / server components",
    "光通信/材料": "Optical communications / materials",
    "封装基板/材料": "Packaging substrates / materials",
    "光通信/数据中心网络": "Optical communications / data-center networking",
    "电子元件/材料": "Electronic components / materials",
    "稀土/材料": "Rare earths / materials",
    "数据中心软件": "Data-center software",
    "铝/材料": "Aluminum / materials",
    "量子计算": "Quantum computing",
    "电力/汽车电驱": "Power / automotive e-drive",
    "电力/机柜热管理": "Power / enclosure thermal management",
    "边缘AI/机器人": "Edge AI / robotics",
    "AI应用/视觉": "AI applications / vision",
    "光纤网络/边缘": "Fiber network / edge",
    "企业AI安全": "Enterprise AI security",
    "散热/热管理": "Thermal management",
    "网络安全/AI安全": "Cybersecurity / AI security",
    "能源/天然气": "Energy / natural gas",
    "AI芯片IP": "AI silicon IP",
    "光通信设备": "Optical communications equipment",
    "电线电缆/材料": "Wire, cable / materials",
    "AI服务器生态": "AI server ecosystem",
    "计算机设备/国产算力": "Computer equipment / domestic compute",
    "锗/半导体材料": "Germanium / semiconductor materials",
    "电源/电力电子": "Power supply / power electronics",
    "AI内容/图像应用": "AI content / image applications",
    "IT分销/云服务": "IT distribution / cloud services",
    "AI内容/大模型应用": "AI content / foundation-model applications",
    "智能座舱/边缘AI": "Smart cockpit / edge AI",
    "比特币/AI算力基础设施": "Bitcoin / AI compute infrastructure",
    "散热/空调": "Cooling / air conditioning",
    "变压器/电力设备": "Transformers / power equipment",
    "UPS/数据中心电源": "UPS / data-center power",
    "存储/模组": "Storage / modules",
    "综合科技/算力": "Technology conglomerate / compute",
    "先进封测": "Advanced packaging and testing",
    "边缘AI SoC": "Edge AI SoC",
    "光伏/电力": "Solar / power",
    "光通信/连接器": "Optical communications / connectors",
    "碳化硅材料": "Silicon carbide materials",
    "电力自动化": "Power automation",
    "检测设备": "Inspection equipment",
    "散热/材料": "Thermal / materials",
}

COUNTRY_REGION = {
    "美国": "美国",
    "中国大陆": "中国大陆",
    "中国台湾": "中国台湾",
    "韩国": "韩国",
    "日本": "日本",
    "英国": "欧洲",
    "荷兰": "欧洲",
    "德国": "欧洲",
    "法国": "欧洲",
    "比利时": "欧洲",
    "挪威": "欧洲",
    "瑞士": "欧洲",
    "爱尔兰": "欧洲",
    "加拿大": "北美",
    "澳大利亚": "亚太",
    "南非": "非洲",
    "哥伦比亚": "拉丁美洲",
    "沙特阿拉伯": "中东",
    "印度": "南亚",
    "意大利": "欧洲",
    "瑞典": "欧洲",
    "西班牙": "欧洲",
    "芬兰": "欧洲",
    "以色列": "以色列",
    "马来西亚": "东南亚",
    "新加坡": "东南亚",
}

COUNTRY_REGION_EN = {
    "美国": "United States",
    "中国大陆": "Mainland China",
    "中国台湾": "Taiwan, China",
    "韩国": "South Korea",
    "日本": "Japan",
    "欧洲": "Europe",
    "以色列": "Israel",
    "东南亚": "Southeast Asia",
    "北美": "North America",
    "亚太": "Asia Pacific",
    "中东": "Middle East",
    "南亚": "South Asia",
}

MANUAL_STAGE = {
    # Core AI compute.
    "NVDA": "accelerator",
    "AMD": "accelerator",
    "AVGO": "accelerator",
    "MRVL": "accelerator",
    "ALAB": "interconnect",
    "CRDO": "interconnect",
    "ARM": "accelerator",
    "688256.SS": "accelerator",
    "688041.SS": "accelerator",
    "9660.HK": "edge",
    # Memory and interfaces.
    "MU": "memory",
    "000660.KS": "memory",
    "005930.KS": "memory",
    "RMBS": "memory",
    "688008.SS": "memory",
    "285A.T": "memory",
    "2408.TW": "memory",
    # Foundry / packaging.
    "2330.TW": "foundry",
    "0981.HK": "foundry",
    "1347.HK": "foundry",
    "GFS": "foundry",
    "2303.TW": "foundry",
    "600584.SS": "packaging",
    "002156.SZ": "packaging",
    "3711.TW": "packaging",
    "AMKR": "packaging",
    # Equipment, materials, power.
    "ASML": "equipment",
    "AMAT": "equipment",
    "LRCX": "equipment",
    "8035.T": "equipment",
    "002371.SZ": "equipment",
    "688012.SS": "equipment",
    "4063.T": "materials",
    "3436.T": "materials",
    "688126.SS": "materials",
    "WOLF": "power",
    "IFX.DE": "power",
    "ON": "power",
    "600460.SS": "power",
    "688396.SS": "power",
    # Cloud, data centers, servers and infrastructure.
    "MSFT": "cloud",
    "GOOGL": "cloud",
    "AMZN": "cloud",
    "META": "cloud",
    "ORCL": "cloud",
    "IBM": "cloud",
    "BABA": "cloud",
    "0700.HK": "cloud",
    "9888.HK": "cloud",
    "EQIX": "cloud",
    "DLR": "cloud",
    "GDS": "cloud",
    "VNET": "cloud",
    "SMCI": "server",
    "DELL": "server",
    "HPE": "server",
    "2382.TW": "server",
    "3231.TW": "server",
    "6669.TW": "server",
    "2356.TW": "server",
    "2317.TW": "server",
    "4938.TW": "server",
    "ANET": "interconnect",
    "CSCO": "interconnect",
    "NTAP": "memory",
    "PSTG": "memory",
    "VRT": "power",
    "ETN": "power",
    "SU.PA": "power",
    "ABBN.SW": "power",
    "6503.T": "power",
    "3017.TW": "power",
    "AAPL": "edge",
    "TSLA": "edge",
    "PLTR": "cloud",
    "CRM": "cloud",
    "NOW": "cloud",
    "SAP": "cloud",
    "SIE.DE": "other",
    "CAT": "power",
    "GEV": "power",
    "NEE": "power",
    "CEG": "power",
    "VST": "power",
    "FSLR": "power",
    "BE": "power",
    "AEP": "power",
    "DUK": "power",
    "ETR": "power",
    "VZ": "interconnect",
    "T": "interconnect",
    "CMCSA": "interconnect",
    "BX": "cloud",
    "KKR": "cloud",
    "PLD": "cloud",
    "DBRG": "cloud",
    "IRM": "cloud",
    "BHP": "materials",
    "RIO": "materials",
    "FCX": "materials",
    "CCJ": "power",
    "0941.HK": "cloud",
    "300750.SZ": "power",
    "300308.SZ": "interconnect",
    "300502.SZ": "interconnect",
    "1810.HK": "edge",
    "601138.SS": "server",
    "002594.SZ": "edge",
    "000063.SZ": "interconnect",
    "000977.SZ": "server",
    "0992.HK": "server",
    "002230.SZ": "other",
    "002415.SZ": "edge",
    "002837.SZ": "power",
    "300274.SZ": "power",
    "600406.SS": "power",
    "600845.SS": "cloud",
    "600183.SS": "materials",
    "002463.SZ": "materials",
    "002916.SZ": "materials",
    "002938.SZ": "materials",
    "603296.SS": "server",
    "002281.SZ": "interconnect",
    "000988.SZ": "interconnect",
    "002028.SZ": "power",
    "601877.SS": "power",
    "2222.SR": "power",
    "2308.TW": "power",
    "8035.T": "equipment",
    "HON": "other",
    "6501.T": "power",
    "ENB": "power",
    "ACN": "cloud",
    "BHARTIARTL.NS": "interconnect",
    "0728.HK": "cloud",
    "RR.L": "power",
    "9432.T": "cloud",
    "CMI": "power",
    "APO": "cloud",
    "ENEL.MI": "power",
    "SNOW": "cloud",
    "ECL": "power",
    "TT": "power",
    "601899.SS": "materials",
    "BN": "cloud",
    "000333.SZ": "power",
    "9433.T": "interconnect",
    "LITE": "interconnect",
    "NG.L": "power",
    "3690.HK": "edge",
    "002475.SZ": "materials",
    "NBIS": "cloud",
    "9618.HK": "cloud",
    "HO.PA": "edge",
    "SLB": "power",
    "MQG.AX": "cloud",
    "D": "power",
    "6367.T": "power",
    "CRWV": "cloud",
    "CARR": "power",
    "300394.SZ": "interconnect",
    "6758.T": "edge",
    "JCI": "power",
    "CBRE": "cloud",
    "3037.TW": "materials",
    "300476.SZ": "materials",
    "005380.KS": "edge",
    "LR.PA": "power",
    "CLS": "server",
    "EXC": "power",
    "GLW": "interconnect",
    "JBL": "server",
    "Z74.SI": "cloud",
    "ORA.PA": "cloud",
    "ERIC": "interconnect",
    "4062.T": "materials",
    "TEF.MC": "cloud",
    "CIEN": "interconnect",
    "1024.HK": "edge",
    "TLS.AX": "cloud",
    "PPL": "power",
    "6981.T": "materials",
    "NOK": "interconnect",
    "603993.SS": "materials",
    "1816.HK": "power",
    "0788.HK": "cloud",
    "0762.HK": "cloud",
    "MDB": "cloud",
    "600111.SS": "materials",
    "601985.SS": "power",
    "KEYS": "equipment",
    "NTNX": "cloud",
    "2600.HK": "materials",
    "TU": "cloud",
    "603019.SS": "server",
    "VOD": "cloud",
    "601012.SS": "power",
    "BT-A.L": "cloud",
    "IONQ": "other",
    "600089.SS": "power",
    "002179.SZ": "materials",
    "000938.SZ": "interconnect",
    "JLL": "cloud",
    "BWA": "power",
    "300014.SZ": "power",
    "NVT": "power",
    "BN4.SI": "cloud",
    "301269.SZ": "equipment",
    "0916.HK": "power",
    "300442.SZ": "cloud",
    "9CI.SI": "cloud",
    "600588.SS": "cloud",
    "9880.HK": "edge",
    "U96.SI": "power",
    "0020.HK": "edge",
    "OKLO": "power",
    "0268.HK": "cloud",
    "688082.SS": "equipment",
    "002236.SZ": "edge",
    "601179.SS": "power",
    "000831.SZ": "materials",
    "LUMN": "interconnect",
    "KD": "cloud",
    "AES": "power",
    "AAON": "power",
    "300454.SZ": "cloud",
    "0552.HK": "cloud",
    "NXT.AX": "cloud",
    "MOD": "power",
    "301165.SZ": "interconnect",
    "PANW": "edge",
    "EQT": "power",
    "600905.SS": "power",
    "688521.SS": "accelerator",
    "600498.SS": "interconnect",
    "002130.SZ": "materials",
    "002261.SZ": "server",
    "010950.KS": "power",
    "000066.SZ": "server",
    "002428.SZ": "materials",
    "002851.SZ": "power",
    "000628.SZ": "server",
    "301236.SZ": "cloud",
    "000400.SZ": "power",
    "1357.HK": "edge",
    "000034.SZ": "cloud",
    "300418.SZ": "edge",
    "300496.SZ": "edge",
    "RGTI": "other",
    "MARA": "cloud",
    "IREN": "cloud",
    "BDC": "materials",
    "301018.SZ": "power",
    "688676.SS": "power",
    "002335.SZ": "power",
    "301308.SZ": "memory",
    "600100.SS": "cloud",
    "002185.SZ": "packaging",
    "300458.SZ": "edge",
    "JKS": "power",
    "CCOI": "interconnect",
    "300990.SZ": "power",
    "2533.HK": "edge",
    "002229.SZ": "cloud",
    "002518.SZ": "power",
    "688702.SS": "interconnect",
    "688206.SS": "equipment",
    "301291.SZ": "power",
    "300657.SZ": "server",
    "688561.SS": "edge",
    "300570.SZ": "interconnect",
    "688234.SS": "materials",
    "600268.SS": "power",
    "300068.SZ": "power",
    "002015.SZ": "power",
    "600602.SS": "cloud",
    "688361.SS": "equipment",
    "002065.SZ": "cloud",
    "688158.SS": "cloud",
    "SOUN": "edge",
    "FLNC": "power",
    "CWK": "cloud",
    "300499.SZ": "power",
    "300602.SZ": "materials",
}


def split_name(name):
    parts = name.split()
    if not parts:
        return name, name
    en = []
    zh = []
    for part in parts:
        if any("\u4e00" <= ch <= "\u9fff" for ch in part):
            zh.append(part)
        else:
            en.append(part)
    return (" ".join(zh) or name, " ".join(en) or name)


def infer_stage(ticker, seg):
    if ticker in MANUAL_STAGE:
        return MANUAL_STAGE[ticker]
    text = seg.lower()
    if any(k in text for k in ["云", "数据中心", "idc", "reit"]):
        return "cloud"
    if any(k in text for k in ["服务器", "oem", "odm", "整机"]):
        return "server"
    if any(k in text for k in ["gpu", "ai芯片", "dcu", "cpu", "fpga", "asic", "ip架构"]):
        return "accelerator"
    if any(k in text for k in ["hbm", "存储", "dram", "nand", "内存"]):
        return "memory"
    if any(k in text for k in ["互连", "光", "网络"]):
        return "interconnect"
    if any(k in text for k in ["代工", "晶圆"]):
        return "foundry"
    if any(k in text for k in ["封测", "封装"]):
        return "packaging"
    if any(k in text for k in ["设备", "光刻", "刻蚀", "检测", "测试", "量测", "cmp", "mocvd"]):
        return "equipment"
    if any(k in text for k in ["材料", "硅片", "衬底", "真空", "零部件"]):
        return "materials"
    if any(k in text for k in ["功率", "电源", "碳化硅", "散热", "冷却", "液冷", "电力", "ups"]):
        return "power"
    if any(k in text for k in ["soc", "车规", "mcu", "射频", "传感", "显示"]):
        return "edge"
    return "other"


def enrich_company(ticker, name, country, city, seg):
    name_zh, name_en = split_name(name)
    stage = infer_stage(ticker, seg)
    region = COUNTRY_REGION.get(country, country)
    return {
        "name_zh": name_zh,
        "name_en": name_en,
        "country_en": COUNTRY_EN.get(country, country),
        "region": region,
        "region_en": COUNTRY_REGION_EN.get(region, region),
        "seg_en": SEGMENT_EN.get(seg, seg),
        "chain": STAGE_BY_KEY[stage]["zh"],
        "chain_en": STAGE_BY_KEY[stage]["en"],
        "chain_key": stage,
    }
